# Generated by Django 5.0.6 on 2024-06-30 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_borrow_date_book_borrow_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='borrow',
            field=models.BooleanField(default=False),
        ),
    ]
